# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        movie:
            properties:
                id: { type: integer }
                name: { type: text }
                synopsis: { type: text }
                coverPath: { type: text }
                genres:
                    type: nested
                    properties:
                        name: { type: text }
                        id: { type: integer }
            persistence:
                driver: orm
                model: App\Entity\Movie
                listener:
                    insert: false

        genre:
            properties:
                id: { type: integer }
                name: { type: text }
                movies:
                    type: nested
                    properties:
                        name: { type: text }
                        synopsis: { type: text }
                        id: { type: integer }
            persistence:
                driver: orm
                model: App\Entity\Genre
                listener:
                    insert: false
